import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

class AlertManager:
    def __init__(self, sender_email, sender_password, to_email):
        self.sender_email = sender_email
        self.sender_password = sender_password
        self.to_email = to_email

        # Email configurations
        self.smtp_server = "smtp.gmail.com"
        self.smtp_port = 465 

    def process_alerts(self, alerts_df):
        '''
        Formats triggered alerts for the terminal and sends an email notification
        Parameters:
            alerts_df: Tickers to alert (pandas.DataFrame)
        Return:
            None
        '''

        # Check if there are tickers to alert
        if alerts_df is None or alerts_df.empty:
            print(f"[{datetime.now().strftime('%H:%M:%S')}] Scan complete: No extreme drops detected.")
            return
        
        # Print to terminal
        self.print_terminal(alerts_df)
        
        # Send an email
        self.send_email(alerts_df)

    def print_terminal(self, alerts_df):
        '''
        Print to the terminal
        Parameters:
            alerts_df: Tickers to alert (pandas.DataFrame)
        Return:
            None
        '''

        # Format the header
        print('\n' + '='*55)
        print(f'Threshold')
        print(f"Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print('='*55)

        # Format the output
        for _, row in alerts_df.iterrows():
            ticker = row['Ticker']
            live_price = row['Live_Price']
            prev_close = row['Prev_Close']
            
            # Format decimals into percentages
            live_return_pct = row['Live_Return'] * 100
            threshold_pct = row['Percentile_Threshold'] * 100

            print(f'{ticker:<10} | Drop: {live_return_pct:>6.2f}% | Limit: {threshold_pct:>6.2f}%')
            print(f'   Live Price: ${live_price:.2f}  (Prev Close: ${prev_close:.2f})')
            print('-' * 55)


    def send_email(self, alerts_df):
        '''
        Helper function to build an HTML email and send it
        '''

        # Check if the email system is well defined
        if not self.sender_email or not self.sender_password or not self.to_email:
            print('Email information is missing.')
            return

        # Define the subject
        subject = f' ALERT: {len(alerts_df)} Stocks Breached Extreme Drop Thresholds'
        
        # Build an HTML Table for the email body
        html = '''
        <html>
          <body style="font-family: Arial, sans-serif;">
            <h2 style="color: #d9534f;">Threshold Alerts</h2>
            <table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse;">
              <tr style="background-color: #f2f2f2;">
                <th>Ticker</th>
                <th>Live Drop</th>
                <th>Threshold</th>
                <th>Live Price</th>
                <th>Prev Close</th>
              </tr>
        '''
        
        # Add a row for each ticker
        for _, row in alerts_df.iterrows():
            html += f"""
              <tr>
                <td><strong>{row['Ticker']}</strong></td>
                <td style="color: red; font-weight: bold;">{row['Live_Return']*100:.2f}%</td>
                <td>{row['Percentile_Threshold']*100:.2f}%</td>
                <td>${row['Live_Price']:.2f}</td>
                <td>${row['Prev_Close']:.2f}</td>
              </tr>
            """
            
        html += """
            </table>
            <p style="font-size: 12px; color: gray;">Generated by Threshold Alert System</p>
          </body>
        </html>
        """

        # Construct message
        msg = MIMEMultipart()
        msg['From'] = self.sender_email
        msg['To'] = self.to_email
        msg['Subject'] = subject
        msg.attach(MIMEText(html, 'html'))

        # Send email
        try:
            context = ssl.create_default_context()
            with smtplib.SMTP_SSL(self.smtp_server, self.smtp_port, context=context) as server:
                server.login(self.sender_email, self.sender_password)
                server.sendmail(self.sender_email, self.to_email, msg.as_string())
            print("Email alert successfully sent.")
        except Exception as e:
            print(f"Failed to send email alert: {e}")